[package]
name = "ncmdump"
version = "0.4.0"
authors = ["iqiziqi <iqiziqi@outlook.com>"]
edition = "2021"

description = "Some copyright protection file dump."
homepage = "https://github.com/iqiziqi/ncmdump.rs"
documentation = "https://docs.rs/ncmdump"
repository = "https://github.com/iqiziqi/ncmdump.rs"
license = "MIT"
readme = "README.md"
keywords = ["ncm", "qmc", "music", "dump"]
exclude = [
    ".editorconfig",
    ".github/**/*",
    "*.ncm"
]

[dependencies]
aes = "^0.8"
anyhow = "^1.0"
base64 = "^0.21"
cipher = { version = "^0.4", features = ["alloc", "block-padding"] }
clap = { version = "^4.1", features = ["derive"] }
glob = "^0.3"
indicatif = "0.17"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^1.0"

[features]
default = ['ncmdump', 'qmcdump']
ncmdump = []
qmcdump = []
